### ISSUE TITLE
Adding a button card

### ISSUE THREAD

**Issue by Markobu98** [wassy92x/lovelace-ha-dashboard#7]
I am trying to add a button card to the sidebar. This is the yaml:

```
views:
  - title: Home
    path: kiosk
    background: center / cover no-repeat url("/local/img/background.png") fixed
    type: custom:ha-dashboard
    sidebar:
      stickyCards:
        - type: custom:digital-clock
      cards:
        - type: weather-forecast
          entity: weather.home
        - type: glance
          entities:
            - entity: sensor.restmull
            - entity: sensor.blauetonne
            - entity: sensor.gelbetonne
        **- type: button
          tap_action:
            action: navigate
            navigation_path: network
          entity: input_boolean.home
          icon: mdi:server-network**
```

However I am unable to save the changes.
